import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import HeaderAuth from "@/components/headerAuth/HeaderAuth";

// import { Provider } from "react-redux";
// import store from "@/redux/store";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const authenticated = false;

  return (
    <html lang="en" data-arp="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Provider store={store}>           */}
          {
            authenticated ? (
              <HeaderAuth />
            ) : (
              <Header />
            )
          }
          {children}
          <Footer />
        {/* </Provider> */}
      </body>
    </html>
  );
}
